# Generated by Django 5.2.15 on 2026-06-22 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_transaction_user_status_idx_transaction_user_id_08c743_idx_and_more'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100)),
                ('token_units', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('token_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meter_number', models.CharField(db_index=True, max_length=20)),
                ('stron_receipt_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stron_response', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gas_token', to='payments.transaction')),
            ],
            options={
                'db_table': 'tokens',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StronTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_number', models.CharField(db_index=True, max_length=20)),
                ('action', models.CharField(choices=[('query_customer_info', 'Query Customer Info'), ('query_meter_info', 'Query Meter Info'), ('query_meter_credit', 'Query Meter Credit'), ('query_customer_credit', 'Query Customer Credit'), ('vending_preview', 'Vending Preview'), ('vending_purchase', 'Vending Purchase'), ('vending_meter', 'Vending Meter'), ('clear_credit', 'Clear Credit'), ('clear_tamper', 'Clear Tamper')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('initiated_by_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stron_logs', to='payments.transaction')),
            ],
            options={
                'db_table': 'stron_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ElectricityToken',
        ),
    ]
