# Generated by Django for Stron direct vending audit actions.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tokens", "0002_gastoken_strontransaction_delete_electricitytoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strontransaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("query_customer_info", "Query Customer Info"),
                    ("query_meter_info", "Query Meter Info"),
                    ("query_meter_credit", "Query Meter Credit"),
                    ("query_customer_credit", "Query Customer Credit"),
                    ("vending_preview", "Vending Preview"),
                    ("vending_purchase", "Vending Purchase"),
                    ("vending_meter", "Vending Meter"),
                    ("vending_direct", "Vending Direct"),
                    ("clear_credit", "Clear Credit"),
                    ("clear_tamper", "Clear Tamper"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
