# Generated by Django 5.2.15 on 2026-06-22 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meters', '0002_gas_meter_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_date', models.DateTimeField(db_index=True)),
                ('units_consumed', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('credit_remaining', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('balance_remaining', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(default='stron', max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meter_readings',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.RenameIndex(
            model_name='meter',
            new_name='meters_meter_n_f2ace4_idx',
            old_name='meters_meter_n_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='meter',
            new_name='meters_user_id_95de62_idx',
            old_name='meters_user_id_def456_idx',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='utility_provider',
        ),
        migrations.AddField(
            model_name='meter',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='meter',
            name='current_credit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='meter',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='meter',
            name='estate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='meter',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='landlord',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_meters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='last_vending_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_serial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='meter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='meter',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('offline', 'Offline'), ('tampered', 'Tampered'), ('maintenance', 'Maintenance')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='meter',
            name='stron_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='meter',
            name='tamper_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meter',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_meters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='valve_status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='meter',
            name='meter_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=20),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['landlord', 'status'], name='meters_landlor_d4e1ad_idx'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='meters.meter'),
        ),
    ]
