# Generated by manual edit to enforce unique meter numbers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meters", "0003_meterreading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meter",
            name="meter_number",
            field=models.CharField(max_length=20, db_index=True, unique=True),
        ),
        migrations.AlterModelOptions(
            name="meter",
            options={
                "db_table": "meters",
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(fields=["user", "is_active"], name="meters_user_id_95de62_idx"),
                    models.Index(fields=["landlord", "status"], name="meters_landlor_d4e1ad_idx"),
                ],
            },
        ),
    ]
