# Generated by Django 5.2.15 on 2026-06-22 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_action_391715_idx',
            old_name='audit_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_user_id_fbfd51_idx',
            old_name='audit_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs_resourc_bda8a6_idx',
            old_name='audit_resource_idx',
        ),
    ]
