# Generated by Django 5.2.15 on 2026-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_user_id_08c743_idx',
            old_name='transaction_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_referen_c33c6b_idx',
            old_name='transaction_reference_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='transaction_created_5c02ac_idx',
            old_name='transaction_created_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_credit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expected_units',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='mpesa_transactions',
        ),
    ]
